import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Game from '../models/Game.js';
import { connectDB } from '../config/db.js';

dotenv.config();

const games = [
  {
    title: "Grand Theft Auto V",
    developer: "Rockstar Games",
    genre: "Action-Adventure",
    description: "Experience Los Santos in this open-world action game. Play through an epic story following three criminals, or explore the vast city with complete freedom.",
    releaseYear: 2013,
    releaseDate: "September 17, 2013",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg",
    trailerUrl: "https://www.youtube.com/embed/QkkoHAzjnUs",
    rating: "M",
    reviewScore: 4.8,
    reviewCount: 156000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Open World Exploration", "Multiple Playable Characters", "Online Multiplayer", "Extensive Customization", "Dynamic Weather System"],
    downloadLink: "https://store.steampowered.com/app/271590/Grand_Theft_Auto_V/"
  },
  {
    title: "Cyberpunk 2077",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    description: "Become a cyberpunk mercenary in Night City, a megalopolis obsessed with power, glamour, and body modification. Explore a vast open world and shape your destiny.",
    releaseYear: 2020,
    releaseDate: "December 10, 2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2rpf.jpg",
    trailerUrl: "https://www.youtube.com/embed/8X2kIfS6fb8",
    rating: "M",
    reviewScore: 4.5,
    reviewCount: 89000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Screen Reader", "Subtitles"],
    features: ["Character Customization", "Multiple Endings", "Cybernetic Enhancements", "Photo Mode", "Dynamic Night City"],
    downloadLink: "https://store.steampowered.com/app/1091500/Cyberpunk_2077/"
  },
  {
    title: "God of War (2018)",
    developer: "Sony Interactive Entertainment",
    genre: "Action-Adventure",
    description: "Journey through Norse mythology as Kratos and his son Atreus. Experience intense combat, solve environmental puzzles, and uncover a deeply emotional story.",
    releaseYear: 2018,
    releaseDate: "April 20, 2018",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r76.jpg",
    trailerUrl: "https://www.youtube.com/embed/K0u_kAWLJOA",
    rating: "M",
    reviewScore: 4.9,
    reviewCount: 124000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Screen Reader", "Subtitles", "One-Handed Mode"],
    features: ["Norse Mythology Setting", "Father-Son Story", "RPG Elements", "Leviathan Axe Combat", "New Game+"],
    downloadLink: "https://store.steampowered.com/app/1593500/God_of_War/"
  },
  {
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    genre: "Action-Adventure",
    description: "Experience the decline of the outlaw era in this epic tale of honor and loyalty. Explore the vast American frontier in this critically acclaimed open-world adventure.",
    releaseYear: 2018,
    releaseDate: "October 26, 2018",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r6i.jpg",
    trailerUrl: "https://www.youtube.com/embed/eaW0tYpxyp0",
    rating: "M",
    reviewScore: 4.9,
    reviewCount: 178000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Massive Open World", "Deep Story Campaign", "Online Multiplayer", "Hunting & Survival", "Dynamic Honor System"],
    downloadLink: "https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/"
  },
  {
    title: "Fortnite",
    developer: "Epic Games",
    genre: "Battle Royale",
    description: "Join millions of players in the ultimate battle royale experience. Build, fight, and survive in this free-to-play multiplayer game with constant updates and events.",
    releaseYear: 2017,
    releaseDate: "July 25, 2017",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.jpg",
    trailerUrl: "https://www.youtube.com/embed/WJW-bzXZM8M",
    rating: "T",
    reviewScore: 4.3,
    reviewCount: 245000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Voice Control", "Subtitles"],
    features: ["100 Player Battles", "Building Mechanics", "Regular Updates", "Cross-Platform Play", "Creative Mode"],
    downloadLink: "https://www.epicgames.com/fortnite/"
  },
  {
    title: "Minecraft",
    developer: "Mojang Studios",
    genre: "Sandbox",
    description: "Build, explore, and survive in an infinite blocky world. Create anything you can imagine, from simple houses to complex redstone contraptions and massive cities.",
    releaseYear: 2011,
    releaseDate: "November 18, 2011",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co49x5.jpg",
    trailerUrl: "https://www.youtube.com/embed/MmB9b5njVbA",
    rating: "E10+",
    reviewScore: 4.7,
    reviewCount: 320000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Screen Reader", "Subtitles"],
    features: ["Infinite World Generation", "Creative & Survival Modes", "Multiplayer Servers", "Redstone Engineering", "Cross-Platform Play"],
    downloadLink: "https://www.minecraft.net/"
  },
  {
    title: "The Last of Us Part II",
    developer: "Naughty Dog",
    genre: "Action-Adventure",
    description: "Industry-leading accessibility with 60+ options including audio descriptions, enhanced listen mode, high contrast displays, and comprehensive screen reader support.",
    releaseYear: 2020,
    releaseDate: "June 19, 2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7f.jpg",
    trailerUrl: "https://www.youtube.com/embed/vhII1qlcZ4E",
    rating: "M",
    reviewScore: 4.9,
    reviewCount: 89000,
    accessibilityFeatures: ["Hearing", "Dexterity", "Visual", "Cognitive", "Colorblind", "Voice Control", "Custom Controls", "Subtitles", "One-Handed"],
    features: ["Audio Descriptions", "Navigation Assist", "Enhanced Listen Mode", "Lock-on Aim", "Auto-Pickup", "60+ Settings"],
    downloadLink: "https://www.playstation.com/en-us/games/the-last-of-us-part-ii/"
  },
  {
    title: "Horizon Zero Dawn",
    developer: "Guerrilla Games",
    genre: "Action RPG",
    description: "Explore a lush post-apocalyptic world overrun by robotic creatures. Hunt machines, uncover ancient mysteries, and discover your true purpose.",
    releaseYear: 2017,
    releaseDate: "February 28, 2017",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7a.jpg",
    trailerUrl: "https://www.youtube.com/embed/u4-FCsiF5x4",
    rating: "T",
    reviewScore: 4.6,
    reviewCount: 95000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Machine Hunting", "Crafting System", "Skill Trees", "Photo Mode", "New Game+"],
    downloadLink: "https://store.steampowered.com/app/1151640/Horizon_Zero_Dawn_Complete_Edition/"
  },
  {
    title: "Spider-Man",
    developer: "Insomniac Games",
    genre: "Action-Adventure",
    description: "Swing through New York City as the iconic web-slinger. Fight crime, save the city, and experience an original Spider-Man story.",
    releaseYear: 2018,
    releaseDate: "September 7, 2018",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7b.jpg",
    trailerUrl: "https://www.youtube.com/embed/q4GdJVvdxss",
    rating: "T",
    reviewScore: 4.8,
    reviewCount: 112000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles", "One-Handed Mode"],
    features: ["Web-Swinging Traversal", "Fluid Combat System", "Suit Customization", "Photo Mode", "DLC Story Content"],
    downloadLink: "https://store.steampowered.com/app/1817070/Marvels_SpiderMan_Remastered/"
  },
  {
    title: "The Witcher 3: Wild Hunt",
    developer: "CD Projekt Red",
    genre: "Action RPG",
    description: "Play as Geralt of Rivia, a monster hunter in a vast open world. Make choices that shape the story and explore a rich fantasy universe.",
    releaseYear: 2015,
    releaseDate: "May 19, 2015",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg",
    trailerUrl: "https://www.youtube.com/embed/c0i88t0Kacs",
    rating: "M",
    reviewScore: 4.9,
    reviewCount: 198000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Branching Storylines", "Monster Hunting", "Alchemy System", "Gwent Card Game", "Massive DLC Expansions"],
    downloadLink: "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/"
  },
  {
    title: "Assassin's Creed Valhalla",
    developer: "Ubisoft",
    genre: "Action RPG",
    description: "Lead your Viking clan to glory in 9th century England. Raid, build, and conquer in this epic open-world adventure.",
    releaseYear: 2020,
    releaseDate: "November 10, 2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7a.jpg",
    trailerUrl: "https://www.youtube.com/embed/ssrNcwxALS4",
    rating: "M",
    reviewScore: 4.4,
    reviewCount: 67000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Screen Reader", "Subtitles"],
    features: ["Viking Raids", "Settlement Building", "Dual-Wielding Combat", "Mythology Quests", "Photo Mode"],
    downloadLink: "https://store.steampowered.com/app/2208920/Assassins_Creed_Valhalla/"
  },
  {
    title: "Elden Ring",
    developer: "FromSoftware",
    genre: "Action RPG",
    description: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    releaseYear: 2022,
    releaseDate: "February 25, 2022",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    trailerUrl: "https://www.youtube.com/embed/E3Huy2cdih0",
    rating: "M",
    reviewScore: 4.9,
    reviewCount: 145000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Subtitles"],
    features: ["Open World Exploration", "Challenging Combat", "Character Builds", "Multiplayer Co-op", "George R.R. Martin Lore"],
    downloadLink: "https://store.steampowered.com/app/1245620/ELDEN_RING/"
  },
  {
    title: "Hollow Knight",
    developer: "Team Cherry",
    genre: "Metroidvania",
    description: "Explore a vast underground kingdom of bugs and heroes. A beautiful hand-drawn action adventure with challenging combat and deep exploration.",
    releaseYear: 2017,
    releaseDate: "February 24, 2017",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7c.jpg",
    trailerUrl: "https://www.youtube.com/embed/UAO2urG23S4",
    rating: "E10+",
    reviewScore: 4.8,
    reviewCount: 89000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Metroidvania Exploration", "Tight Combat", "Beautiful Art Style", "Challenging Bosses", "Multiple Endings"],
    downloadLink: "https://store.steampowered.com/app/367520/Hollow_Knight/"
  },
  {
    title: "Celeste",
    developer: "Maddy Makes Games",
    genre: "Platformer",
    description: "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer about self-discovery.",
    releaseYear: 2018,
    releaseDate: "January 25, 2018",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7d.jpg",
    trailerUrl: "https://www.youtube.com/embed/iof4fSz2V14",
    rating: "E",
    reviewScore: 4.9,
    reviewCount: 67000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles", "One-Handed Mode"],
    features: ["Tight Platforming", "Assist Mode", "Emotional Story", "Challenging Levels", "Beautiful Soundtrack"],
    downloadLink: "https://store.steampowered.com/app/504230/Celeste/"
  },
  {
    title: "Portal 2",
    developer: "Valve",
    genre: "Puzzle",
    description: "The highly anticipated sequel to the award-winning Portal. Navigate test chambers using the portal gun and solve mind-bending puzzles.",
    releaseYear: 2011,
    releaseDate: "April 19, 2011",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7e.jpg",
    trailerUrl: "https://www.youtube.com/embed/tax4e4hBBZc",
    rating: "E10+",
    reviewScore: 4.9,
    reviewCount: 156000,
    accessibilityFeatures: ["Full Captions", "Subtitles", "Colorblind Mode"],
    features: ["Portal Mechanics", "Co-op Mode", "Engaging Story", "Level Editor", "Hilarious Writing"],
    downloadLink: "https://store.steampowered.com/app/620/Portal_2/"
  },
  {
    title: "Forza Horizon 5",
    developer: "Playground Games",
    genre: "Racing",
    description: "Your ultimate Horizon adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action.",
    releaseYear: 2021,
    releaseDate: "November 5, 2021",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    trailerUrl: "https://www.youtube.com/embed/FYH9n37B7Yw",
    rating: "E",
    reviewScore: 4.7,
    reviewCount: 89000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles", "One-Handed Mode"],
    features: ["Open World Racing", "Hundreds of Cars", "Dynamic Weather", "Online Multiplayer", "Event Creator"],
    downloadLink: "https://store.steampowered.com/app/1551360/Forza_Horizon_5/"
  },
  {
    title: "Civilization VI",
    developer: "Firaxis Games",
    genre: "Strategy",
    description: "Build an empire to stand the test of time. Become Ruler of the World by establishing and leading a civilization from the Stone Age to the Information Age.",
    releaseYear: 2016,
    releaseDate: "October 21, 2016",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg",
    trailerUrl: "https://www.youtube.com/embed/5KdE0p2joJw",
    rating: "E10+",
    reviewScore: 4.6,
    reviewCount: 112000,
    accessibilityFeatures: ["Full Captions", "Colorblind Mode", "Subtitles"],
    features: ["Turn-Based Strategy", "Historical Leaders", "Multiplayer", "Expansive Tech Tree", "Multiple Victory Conditions"],
    downloadLink: "https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/"
  },
  {
    title: "Stardew Valley",
    developer: "ConcernedApe",
    genre: "Simulation",
    description: "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life.",
    releaseYear: 2016,
    releaseDate: "February 26, 2016",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7g.jpg",
    trailerUrl: "https://www.youtube.com/embed/ot7uXNQskhs",
    rating: "E10+",
    reviewScore: 4.9,
    reviewCount: 245000,
    accessibilityFeatures: ["Full Captions", "Colorblind Mode", "Subtitles"],
    features: ["Farming Simulator", "Fishing", "Mining", "Multiplayer", "Romance System"],
    downloadLink: "https://store.steampowered.com/app/413150/Stardew_Valley/"
  },
  {
    title: "Resident Evil 4",
    developer: "Capcom",
    genre: "Horror",
    description: "Six years after the events of Resident Evil 2, Leon S. Kennedy is sent to rescue the U.S. President's daughter from a mysterious cult in rural Spain.",
    releaseYear: 2023,
    releaseDate: "March 24, 2023",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    trailerUrl: "https://www.youtube.com/embed/W1OUs3HwIuo",
    rating: "M",
    reviewScore: 4.8,
    reviewCount: 78000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Subtitles"],
    features: ["Survival Horror", "Intense Combat", "Resource Management", "Multiple Playthroughs", "Additional Modes"],
    downloadLink: "https://store.steampowered.com/app/2050650/Resident_Evil_4/"
  },
  {
    title: "FIFA 24",
    developer: "EA Sports",
    genre: "Sports",
    description: "Experience the beautiful game with unmatched authenticity in EA SPORTS FC 24. Play as the world's greatest players and teams.",
    releaseYear: 2023,
    releaseDate: "September 29, 2023",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    trailerUrl: "https://www.youtube.com/embed/XhP3Xh4LMA8",
    rating: "E",
    reviewScore: 4.2,
    reviewCount: 145000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Ultimate Team", "Career Mode", "Volta Football", "Online Multiplayer", "Realistic Graphics"],
    downloadLink: "https://store.steampowered.com/app/2195250/EA_SPORTS_FC_24/"
  },
  {
    title: "Street Fighter 6",
    developer: "Capcom",
    genre: "Fighting",
    description: "The next evolution of the Street Fighter series! Fight using a variety of classic and new techniques, including the innovative Drive System.",
    releaseYear: 2023,
    releaseDate: "June 2, 2023",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    trailerUrl: "https://www.youtube.com/embed/4jOuvxpK7DI",
    rating: "T",
    reviewScore: 4.7,
    reviewCount: 56000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles", "One-Handed Mode"],
    features: ["Classic Fighting", "World Tour Mode", "Online Ranked", "Custom Characters", "Modern Controls"],
    downloadLink: "https://store.steampowered.com/app/1364780/Street_Fighter_6/"
  },
  {
    title: "Doom Eternal",
    developer: "id Software",
    genre: "Shooter",
    description: "Hell's armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions.",
    releaseYear: 2020,
    releaseDate: "March 20, 2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7h.jpg",
    trailerUrl: "https://www.youtube.com/embed/_Vn59cJcr18",
    rating: "M",
    reviewScore: 4.7,
    reviewCount: 123000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Fast-Paced Combat", "Glory Kills", "Weapon Mods", "Battlemode Multiplayer", "Horde Mode"],
    downloadLink: "https://store.steampowered.com/app/782330/DOOM_Eternal/"
  },
  {
    title: "Subnautica",
    developer: "Unknown Worlds Entertainment",
    genre: "Survival",
    description: "Dive into a vast underwater world filled with wonder and peril. Craft equipment, pilot submarines, and out-smart wildlife to explore lush coral reefs.",
    releaseYear: 2018,
    releaseDate: "January 23, 2018",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.jpg",
    trailerUrl: "https://www.youtube.com/embed/Rz2SNm8VguE",
    rating: "E10+",
    reviewScore: 4.8,
    reviewCount: 178000,
    accessibilityFeatures: ["Full Captions", "Colorblind Mode", "Subtitles"],
    features: ["Underwater Exploration", "Base Building", "Crafting", "Story Mode", "Freedom Mode"],
    downloadLink: "https://store.steampowered.com/app/264710/Subnautica/"
  },
  {
    title: "Hades",
    developer: "Supergiant Games",
    genre: "Roguelike",
    description: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion.",
    releaseYear: 2020,
    releaseDate: "September 17, 2020",
    imageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2r7i.jpg",
    trailerUrl: "https://www.youtube.com/embed/DZNyhqs3CW4",
    rating: "T",
    reviewScore: 4.9,
    reviewCount: 234000,
    accessibilityFeatures: ["Full Captions", "Large Target Inputs", "Colorblind Mode", "Subtitles"],
    features: ["Roguelike Action", "Greek Mythology", "Character Relationships", "Multiple Weapons", "God Mode Difficulty"],
    downloadLink: "https://store.steampowered.com/app/1145360/Hades/"
  }
];

const seedGames = async () => {
  try {
    await connectDB();
    console.log('Connected to database');

    // Clear existing games
    await Game.deleteMany({});
    console.log('Cleared existing games');

    // Insert new games
    await Game.insertMany(games);
    console.log(`Seeded ${games.length} games successfully`);

    process.exit(0);
  } catch (error) {
    console.error('Error seeding games:', error);
    process.exit(1);
  }
};

seedGames();
